"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from dotenv import load_dotenv
from root.config.base_dir import BASE_DIR


load_dotenv()


SECRET_KEY = 'itwvfk4fnf&$1e33zqi7_ad4q^m_$9eivblqz#$aenhi7l^a_d'

DEBUG = True

ALLOWED_HOSTS = ['*']


SHARED_APPS = (
    'tenant_schemas',    # mandatory, should always be before any django app
    'apps.customer',     # mandatory, should always be before any django app

    'django.contrib.contenttypes',

    # everything below here is optional
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.admin',

    'django.contrib.sites',
    'django.contrib.flatpages',

    'sorl.thumbnail',     # Thumbnail generator
    'django_redis',       # Caching
    'debug_toolbar',      # Development
    'django_extensions',  # Development

    'rest_framework',
    'rest_framework.authtoken',

)

# Application definition
TENANT_APPS = (
    'django.contrib.contenttypes',
    'django.contrib.flatpages',
    'django.contrib.staticfiles',
    'apps.blog',
    'django.contrib.admin',

    'django_redis',       # Caching
    'sorl.thumbnail',     # Thumbnail generator
    'debug_toolbar',  # Development
    'django_extensions',  # Development
)

INSTALLED_APPS = (
    'tenant_schemas',  # mandatory, should always be before any django app
    'apps.customer',  # mandatory, should always be before any django app

    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.admin',
    'django.contrib.flatpages',
    'django.contrib.staticfiles',
    'django.forms',

    'apps.blog',

    'django_select2',
    'solo',               # Singleton model manager
    'sorl.thumbnail',     # Thumbnail generator
    'django_redis',       # Caching
    'debug_toolbar',      # Development
    'django_extensions',  # Development

    'rest_framework',
    'rest_framework.authtoken',

)

FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'


MIDDLEWARE = [
    'tenant_schemas.middleware.TenantMiddleware',
    # 'tenant_schemas.middleware.SuspiciousTenantMiddleware',     # tenant_url status 404 => 400
    # 'tenant_schemas.middleware.DefaultTenantMiddleware',        # tenant_url status 404 => public_url
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'root.urls'


WSGI_APPLICATION = 'root.wsgi.application'


from .config.cache import *
from .config.database import *
from .config.default import *
from .config.development import *
from .config.drf import *
from .config.logging import *
from .config.production import *
from .config.project import *
from .config.route import *
from .config.static import *
from .config.templates import *
from .config.tenant import *











